name: Feature Request
description: Suggest an Enhancement to this Sector File
title: "[FEAT]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: "# Feature Request form"
  - type: markdown
    attributes:
      value: "Please make sure to check existing issues on this repo. Only open an issue here if they don't already exist there. Thanks!"
  - type: textarea
    id: context
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context (Optional)
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false

