name: Ground Layout
description: Suggest a Ground Layout Enhancement to this Sector File
title: "[GLYT]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: "# Ground Layout Report form"
  - type: markdown
    attributes:
      value: "Please make sure to check existing issues on this repo. Only open an issue here if they don't already exist there. Thanks!"
  - type: dropdown
    id: related
    attributes:
      label: Are you suggesting a mere update or a new Ground Layout?
      multiple: false
      options:
        - New Ground Layout
        - Update to an existing Ground Layout
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description of the updates required.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (Optional)
      description: If possible, attach screenshots that demonstrate the need.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context (Optional)
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
